#pragma config(Sensor, S1,     touch1,         sensorEV3_Touch)
#pragma config(Sensor, S2,     touch2,         sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

long encoder = 0;
int sensor2 = SensorValue[S2];
int sensor1 = SensorValue[S1];
int i = 0;
bool flag_quadrat = false;


//MOTOR A
task posicioInicialA(){
	if(SensorValue[S1] == 1) { //Estem en la posiciÃ³ inc
		stopMotor(motorA);
	} else if (SensorValue[S1] == 0) { //No estem en la posiciÃ³ inic
		while(SensorValue[S1] == 0) {
			setMotor(motorA, -30);
		}
	}
}

//MOTOR B
task posicioInicialB() {
	if(SensorValue[S2] == 1) {
		stopMotor(motorB);
	}	else if (SensorValue[S2] == 0) {
		while(SensorValue[S2] == 0) {
			setMotor(motorB, -30);
		}
	}
}

//MOTOR C
task posicioInicialC() {
	if(i == 0){
		for(i = 0; i <= 2; i++) {
			moveMotorTarget(motorC, 340, -30);
			waitUntilMotorStop(motorC);
		}
	}	else if (i == 3) {
		setMotor(motorC, 0);
		stopMotor(motorC);
	}
}

//QUADRAT
void quadrat() {
	int capes = 3;
	for(int i = 1; i <= capes; i++){
		moveMotorTarget(motorA, 3000-100*i, 40);
		waitUntilMotorStop(motorA);
		sleep(100);
		moveMotorTarget(motorB, 3000-100*i, 60);
		waitUntilMotorStop(motorB);
		sleep(100);
		moveMotorTarget(motorA, 3000-100*i, -40);
		waitUntilMotorStop(motorA);
		sleep(100);
		moveMotorTarget(motorB, 3000-100*i, -60);
		waitUntilMotorStop(motorB);
		sleep(100);
		moveMotorTarget(motorC, 10, 10);
		sleep(100);
	}
	flag_quadrat = true;
}

task main()
{
	setMotorReversed(motorB, true);

	//while(flag_quadrat == false){
	//	quadrat();
	//}

	//while(true) {
	//	moveMotorTarget(motorA, 2000, 30);
	//	waitUntilMotorStop(motorA);
	//	sleep(100);
	//	moveMotorTarget(motorB, 2000, 30);
	//	moveMotorTarget(motorA, 2000, -10);
	//	waitUntilMotorStop(motorB);
	//	waitUntilMotorStop(motorA);
	//	sleep(100);
	//	moveMotorTarget(motorB, 2000, -30);
	//	moveMotorTarget(motorA, 2000, -10);
	//	waitUntilMotorStop(motorB);
	//	waitUntilMotorStop(motorA);
	//	sleep(100);
	//}

	motor[motorB] = -100;
	sleep(5000);


		//moveMotorTarget(motorC, 10, -10);
		//waitUntilMotorStop(motorC);


}
